site_name: ManishKumar Chetpalli
site_description: Documentation for Data Engineering and Big Data Technologies
site_author: Manishkumar Chetpalli

repo_url: https://github.com/manish-chet
repo_name: "DataEngineering"
edit_uri: edit/main/docs/


copyright: >
  Copyright &copy; 2025 Manishkumar Chetpalli

theme:
  name: material
  logo: assets/images/sqldeveloper-original.svg
  favicon: assets/images/sqldeveloper-original.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.suggest
    - search.share
    - navigation.footer  
    - content.action.feedback 
    - toc.follow
    - toc.extend
  palette:
    - scheme: default
      primary: custom
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Fundamentals:
      - Overview: DataEngineering/DE.md
      - DE Lifecycle: DataEngineering/DEcycle.md
      - DE UnderCurrents: DataEngineering/DEundercurrent.md
      - DE Architecture & Design: DataEngineering/DesigningGDA.md
      - Data Orchestration: airflow/dataorchestration.md
      - Data Warehousing: datawarehousing/overview.md
      - File Formats: DataEngineering/fileformat.md
      - SQL: sql/sql.md
  - Projects:
    - Flight Booking Data Pipeline: projects/FlightBookingDataPipelinewithAirflow&CICD.md
    - Flink Ignite Custom Dialect: projects/flink-ignite.md
    - FastAPI Kafka Producer: projects/kafkaapi.md
  - BigData:  
      - Overview: hadoop/Bigdata.md
      - HDFS:  hadoop/HDFS.md
      - MapReduce: hadoop/mapreduce.md
      - YARN: hadoop/yarn.md
      - Kerberos: hadoop/kerberos.md
      - Hive: hive/overview.md
      - Kafka: kafka/overview.md
      - Ignite: ignite/ignite.md
      - Airflow: airflow/airflow.md
      - Spark: spark/spark.md
      - Mongo: sql/Mongo.md
      - Delta Lake: delta/deltalake.md
  - Cloud computing:
    - Overview: cloud/overview.md
    - Databricks:
      - Overview: cloud/databricks.md
  - System Design:
    - Overview: systemdesign/overview.md
    - Horizonatal vs Vertical Scaling: systemdesign/scaling.md
    - Load Balancing: systemdesign/loadbalancing.md
    - Consistent Hashing: systemdesign/consistenthashing.md
    - Messaging Queue: systemdesign/messagingqueue.md
  - SetupDocs:
    - Airflow Setup: tooling/airflow_install_onpremise.md
    - Ignite Multi Node Setup: tooling/igniteinstall.md
    - Kafka Multi Node Setup: tooling/kafka_install_zookeeper.md
    - Kubernetes Setup: tooling/kubernetes_install.md
    - Sparkstandalone Multi Node Setup: tooling/spark3standalone.md
  - Interview Prep:
    - Hadoop : hadoop/hadoopiq.md
    - Kafka : kafka/iq.md
    - Airflow : airflow/airflowiq.md
    - Flink  : flink/iq.md
    - MongoDB : sql/mongoiq.md
  - About Me: about.md
  
# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/manishkumarchetpalli/
    - icon: fontawesome/brands/github
      link: https://github.com/manish-chet

extra_css:
  - stylesheets/extra.css